INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (1, '试炼之伊始', 0, 10, 0, 0, 'Accept3d', 'nazoplus', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (2, 'Dont Panic', 1, 100, 0, 0, 'Accept3d', '42', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (3, '面向对象设计', 1, 100, 0, 0, 'Accept3d', 'is-a', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (4, '不可见', 1, 100, 0, 0, 'Accept3d', 'negative',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (5, '损坏的二维码', 1, 150, 0, 0, 'Accept3d', 'mucfc_0318',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (6, '颜文字', 3, 150, 0, 0, 'Accept3d', 'mucfc{em0ji_i5_v3ry_cute}', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (7, 'disabled_button', 3, 150, 0, 0, 'Accept3d', 'mucfc_have_fun',1);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (8, 'Veni! Vidi! Vici!', 4, 150, 0, 0, 'Accept3d', 'thegrandeurthatwasrome', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (9, '彩虹表', 4, 200, 0, 0, 'Accept3d', 'strangenessisanecessaryingredientinbeauty',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (10, 'Scientific Witchery', 5, 200, 0, 0, 'Accept3d', '360620266859', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (11, '香霖堂的日常', 5, 200, 0, 0, 'Accept3d', '38521633', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (12, '小猫钓鱼', 5, 200, 0, 0, 'Accept3d', '3122888614582724756462549679766359821315121532',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (13, 'user-agent', 5, 200, 0, 0, 'Accept3d', '4553d27e7c654ce9769933eaa8f7fe2f', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (14, 'cookie', 5, 200, 0, 0, 'Accept3d', 'cat', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (15, 'wasm', 5, 200, 0, 0, 'Accept3d', '32435',1);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (16, 'easyGIF',5 , 200, 0, 0, 'Accept3d', '8bwmqne',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (17, 'easyBMP', 6, 300, 0, 0, 'Accept3d', 'mucfc{our_9oal_i5_th3_univer5e}',0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (18, 'easyReverse', 7, 300, 0, 0, 'Accept3d', 'CrackMeJustForFun', 0);
INSERT INTO puzzle (id, name, unlock_score, score, tried_num, passed_num, author, answer, unique_template) VALUES (19, 'easyXOR', 7, 300, 0, 0, 'Accept3d', 'mucfc{fl4g_is_v3ry_ea5y}',  0);